# Generated by Django 3.2.3 on 2021-06-14 14:00

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_asset', models.CharField(choices=[('USDT', 'USDT')], max_length=5, verbose_name='Первая криптовалюта')),
                ('second_asset', models.CharField(choices=[('BNB', 'BNB'), ('ADA', 'ADA'), ('DOGE', 'DOGE'), ('XRP', 'XRP'), ('DOT', 'DOT'), ('LTC', 'LTC'), ('LINK', 'LINK'), ('SOL', 'SOL'), ('MATIC', 'MATIC'), ('HEX', 'HEX'), ('THETA', 'THETA'), ('XLM', 'XLM'), ('VET', 'VET'), ('ETC', 'ETC'), ('FIL', 'FIL'), ('TRX', 'TRX'), ('EOS', 'EOS'), ('XMR', 'XMR'), ('CAKE', 'CAKE'), ('IOTA', 'IOTA'), ('ATOM', 'ATOM'), ('LUNA', 'LUNA')], max_length=5, verbose_name='Вторая криптовалюта')),
                ('third_asset', models.CharField(choices=[('BTC', 'BTC')], max_length=5, verbose_name='Третья криптовалюта')),
                ('secret_key', models.CharField(max_length=256, verbose_name='Секретный ключ')),
                ('api_key', models.CharField(max_length=256, verbose_name='API ключ')),
                ('return_on_sales', models.DecimalField(decimal_places=2, max_digits=5, validators=[bot.models.validate_percent], verbose_name='Процент прибыли, %')),
                ('trade_balance', models.DecimalField(decimal_places=2, max_digits=7, validators=[bot.models.validate_trade_balance], verbose_name='Торговый баланс')),
                ('bot_name', models.CharField(max_length=100, verbose_name='Имя бота')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания бота')),
                ('activity', models.BooleanField(default=False, verbose_name='Вкл./Выкл. бота')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['-create_at'],
            },
        ),
    ]
