# Generated by Django 3.2.3 on 2021-06-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbot',
            options={'ordering': ['-create_at'], 'verbose_name': 'Бота', 'verbose_name_plural': 'Боты'},
        ),
        migrations.CreateModel(
            name='BotProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs_deal', models.TextField()),
                ('deal_time', models.DateTimeField(auto_now_add=True, verbose_name='Время сделки')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.addbot')),
            ],
            options={
                'ordering': ['-deal_time'],
            },
        ),
    ]
