# Generated by Django 3.2.3 on 2021-07-02 06:32

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbot',
            name='bot_name',
            field=models.CharField(default=1659, max_length=100, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='addbot',
            name='qty_3',
            field=models.CharField(default='1.000000', max_length=8, verbose_name='minQty третей пары'),
        ),
        migrations.AlterField(
            model_name='addbot',
            name='second_asset',
            field=models.CharField(choices=[('POLS', 'POLS')], max_length=5, verbose_name='Вторая криптовалюта'),
        ),
        migrations.AlterField(
            model_name='addbot',
            name='trade_balance',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7, validators=[bot.models.validate_trade_balance], verbose_name='Торговый баланс'),
        ),
    ]
