# Generated by Django 3.2.3 on 2021-06-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210625_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botprofit',
            name='bot',
        ),
    ]
