# Generated by Django 3.2.4 on 2021-07-09 12:13

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210707_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbotbnb',
            options={'ordering': ['-create_at'], 'verbose_name': 'Бот BNB', 'verbose_name_plural': 'Боты BNB'},
        ),
        migrations.AlterModelOptions(
            name='botprofit',
            options={'ordering': ['-deal_time'], 'verbose_name': 'Логи работы бота Binance', 'verbose_name_plural': 'Логи работы бота Binance'},
        ),
        migrations.AlterField(
            model_name='addbotbnb',
            name='bot_name',
            field=models.CharField(default=20609, max_length=100, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='addbotbnb',
            name='qty_3',
            field=models.CharField(default='1.0000', max_length=8, verbose_name='minQty третей пары'),
        ),
        migrations.AlterField(
            model_name='addbotbnb',
            name='return_on_sales',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, validators=[bot.models.validate_percent], verbose_name='Процент прибыли, %'),
        ),
        migrations.AlterField(
            model_name='addbotbnb',
            name='second_asset',
            field=models.CharField(choices=[('MDX', 'MDX'), ('FTM', 'FTM'), ('ADA', 'ADA'), ('XRP', 'XRP'), ('DOT', 'DOT'), ('BOND', 'BOND'), ('BCH', 'BCH'), ('SOL', 'SOL'), ('LTC', 'LTC'), ('MATIC', 'MATIC'), ('ETC', 'ETC'), ('ICP', 'ICP'), ('THETA', 'THETA'), ('XLM', 'XLM'), ('VET', 'VET'), ('FIL', 'FIL'), ('TRX', 'TRX'), ('AAVE', 'AAVE'), ('XMR', 'XMR'), ('EOS', 'EOS'), ('CAKE', 'CAKE'), ('MKR', 'MKR'), ('ALGO', 'ALGO'), ('ATOM', 'ATOM'), ('FTT', 'FTT'), ('NEO', 'NEO'), ('IOTA', 'IOTA'), ('XTZ', 'XTZ'), ('UNI', 'UNI'), ('AVAX', 'AVAX'), ('KSM', 'KSM'), ('WAVES', 'WAVES'), ('EGLD', 'EGLD'), ('HBAR', 'HBAR'), ('CHZ', 'CHZ'), ('ZEC', 'ZEC'), ('DASH', 'DASH'), ('YFI', 'YFI'), ('SNX', 'SNX'), ('SUSHI', 'SUSHI'), ('ENJ', 'ENJ'), ('NEAR', 'NEAR'), ('ZIL', 'ZIL'), ('AXS', 'AXS'), ('CRV', 'CRV'), ('ZEN', 'ZEN'), ('DGB', 'DGB'), ('ONT', 'ONT'), ('ICX', 'ICX'), ('BAKE', 'BAKE'), ('ANKR', 'ANKR'), ('RVN', 'RVN'), ('AR', 'AR'), ('LPT', 'LPT'), ('RSR', 'RSR'), ('WRX', 'WRX'), ('KAVA', 'KAVA')], max_length=5, verbose_name='Вторая криптовалюта'),
        ),
        migrations.AlterField(
            model_name='addbotbnb',
            name='third_asset',
            field=models.CharField(default='BNB', max_length=5, verbose_name='Третья криптовалюта'),
        ),
        migrations.AlterField(
            model_name='addbotbnb',
            name='trade_balance',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=7, validators=[bot.models.validate_trade_balance], verbose_name='Торговый баланс'),
        ),
        migrations.AlterField(
            model_name='addbotbtc',
            name='bot_name',
            field=models.CharField(default=4383, max_length=100, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='addbotbtc',
            name='return_on_sales',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, validators=[bot.models.validate_percent], verbose_name='Процент прибыли, %'),
        ),
        migrations.AlterField(
            model_name='addbotbtc',
            name='second_asset',
            field=models.CharField(choices=[('XEM', 'XEM'), ('HNT', 'HNT'), ('CHZ', 'CHZ'), ('MANA', 'MANA'), ('ONE', 'ONE'), ('MATIC', 'MATIC'), ('ZEN', 'ZEN'), ('FTM', 'FTM'), ('CELO', 'CELO'), ('STX', 'STX'), ('RUNE', 'RUNE'), ('PERP', 'PERP'), ('FTM', 'FTM'), ('NANO', 'NANO'), ('ONT', 'ONT'), ('ENJ', 'ENJ'), ('WAVES', 'WAVES'), ('CTSI', 'CTSI'), ('ICX', 'ICX'), ('ALGO', 'ALGO'), ('SNX', 'SNX'), ('LRC', 'LRC'), ('GRT', 'GRT'), ('HIVE', 'HIVE'), ('XTZ', 'XTZ'), ('HBAR', 'HBAR'), ('BZRX', 'BZRX'), ('IOTA', 'IOTA'), ('PAXG', 'PAXG'), ('OGN', 'OGN'), ('CRV', 'CRV'), ('KMD', 'KMD'), ('ONE', 'ONE'), ('CELR', 'CELR'), ('GTC', 'GTC'), ('SKL', 'SKL'), ('BAT', 'BAT'), ('XEM', 'XEM'), ('MDX', 'MDX'), ('ZRX', 'ZRX'), ('QTUM', 'QTUM'), ('FORTH', 'FORTH'), ('LTO', 'LTO'), ('AVAX', 'AVAX'), ('MTL', 'MTL'), ('STPT', 'STPT'), ('COTI', 'COTI'), ('STORJ', 'STORJ'), ('TLM', 'TLM'), ('MKR', 'MKR'), ('BAL', 'BAL'), ('RLC', 'RLC'), ('STX', 'STX'), ('ZEN', 'ZEN'), ('BAKE', 'BAKE'), ('KAVA', 'KAVA'), ('TOMO', 'TOMO'), ('PERL', 'PERL'), ('MANA', 'MANA'), ('BAND', 'BAND'), ('DCR', 'DCR'), ('SRM', 'SRM'), ('AXS', 'AXS'), ('UMA', 'UMA'), ('DGB', 'DGB'), ('FTT', 'FTT'), ('ANT', 'ANT'), ('RSR', 'RSR'), ('FIO', 'FIO'), ('SRM', 'SRM'), ('NEAR', 'NEAR'), ('BLZ', 'BLZ'), ('TWT', 'TWT'), ('RVN', 'RVN'), ('CVC', 'CVC'), ('WRX', 'WRX'), ('XVS', 'XVS'), ('REN', 'REN'), ('ONG', 'ONG'), ('NMR', 'NMR'), ('SAND', 'SAND'), ('ARDR', 'ARDR'), ('KNC', 'KNC'), ('ONG', 'ONG'), ('STRAX', 'STRAX'), ('DATA', 'DATA'), ('ALICE', 'ALICE'), ('TRU', 'TRU'), ('INJ', 'INJ'), ('BEL', 'BEL'), ('CTK', 'CTK'), ('BTG', 'BTG'), ('CHR', 'CHR'), ('CTXC', 'CTXC'), ('ANKR', 'ANKR'), ('POLS', 'POLS'), ('TRB', 'TRB'), ('PSG', 'PSG'), ('LINA', 'LINA'), ('OXT', 'OXT'), ('UTK', 'UTK'), ('HNT', 'HNT'), ('JUV', 'JUV'), ('AR', 'AR'), ('COS', 'COS'), ('YFII', 'YFII'), ('AVA', 'AVA'), ('FIRO', 'FIRO'), ('DEGO', 'DEGO'), ('FIS', 'FIS'), ('DNT', 'DNT'), ('AUTO', 'AUTO'), ('FLM', 'FLM'), ('IRIS', 'IRIS'), ('ATM', 'ATM'), ('BAR', 'BAR'), ('NBS', 'NBS'), ('COS', 'COS'), ('HARD', 'HARD'), ('PNT', 'PNT'), ('MIR', 'MIR'), ('UNFI', 'UNFI'), ('LPT', 'LPT'), ('OG', 'OG'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('ADA', 'ADA'), ('XRP', 'XRP'), ('DOGE', 'DOGE'), ('DOT', 'DOT'), ('SOL', 'SOL'), ('LTC', 'LTC'), ('LINK', 'LINK'), ('ETC', 'ETC'), ('KSM', 'KSM'), ('VET', 'VET'), ('AAVE', 'AAVE'), ('TFUEL', 'TFUEL'), ('COMP', 'COMP'), ('FET', 'FET'), ('BCH', 'BCH'), ('RUNE', 'RUNE'), ('EOS', 'EOS'), ('ARPA', 'ARPA'), ('NULS', 'NULS'), ('TKO', 'TKO'), ('OM', 'OM'), ('AION', 'AION'), ('GXS', 'GXS'), ('WING', 'WING'), ('REP', 'REP'), ('SFP', 'SFP'), ('GTO', 'GTO'), ('ORN', 'ORN'), ('CFX', 'CFX'), ('ROSE', 'ROSE'), ('WAN', 'WAN'), ('BOND', 'BOND'), ('POND', 'POND'), ('BTS', 'BTS'), ('WTC', 'WTC'), ('XMR', 'XMR'), ('UNI', 'UNI'), ('THETA', 'THETA'), ('SUSHI', 'SUSHI'), ('FIL', 'FIL'), ('NEO', 'NEO'), ('CHZ', 'CHZ'), ('TRX', 'TRX'), ('ZIL', 'ZIL'), ('ATOM', 'ATOM'), ('XLM', 'XLM'), ('CELO', 'CELO'), ('SXP', 'SXP'), ('LUNA', 'LUNA'), ('1INCH', '1INCH'), ('YFI', 'YFI'), ('OMG', 'OMG'), ('BNT', 'BNT'), ('CAKE', 'CAKE')], max_length=5, verbose_name='Вторая криптовалюта'),
        ),
        migrations.AlterField(
            model_name='addbotbtc',
            name='trade_balance',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=7, validators=[bot.models.validate_trade_balance], verbose_name='Торговый баланс'),
        ),
        migrations.AlterField(
            model_name='addboteth',
            name='bot_name',
            field=models.CharField(default=11962, max_length=100, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='addboteth',
            name='return_on_sales',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, validators=[bot.models.validate_percent], verbose_name='Процент прибыли, %'),
        ),
        migrations.AlterField(
            model_name='addboteth',
            name='trade_balance',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=7, validators=[bot.models.validate_trade_balance], verbose_name='Торговый баланс'),
        ),
    ]
