# FIRST_CHOISE_ETH = [
#     ('USDT', 'USDT'),
# ]

SECOND_CHOISE_BNB = [
    ('AXS', 'AXS'),
    ('CRV', 'CRV'),
    ('ZEN', 'ZEN'),
    ('DGB', 'DGB'),
    ('ONT', 'ONT'),
    ('ICX', 'ICX'),
    ('BAKE', 'BAKE'),
    ('ANKR', 'ANKR'),
    ('RVN', 'RVN'),
    ('AR', 'AR'),
    ('LPT', 'LPT'),
    ('RSR', 'RSR'),
    ('WRX', 'WRX'),
    ('KAVA', 'KAVA'),
    #
    ('ADA', 'ADA'),
    ('XRP', 'XRP'),
    ('DOT', 'DOT'),
    ('BOND', 'BOND'),
    ('BCH', 'BCH'),
    ('SOL', 'SOL'),
    ('LTC', 'LTC'),
    ('MATIC', 'MATIC'),
    ('ETC', 'ETC'),
    ('ICP', 'ICP'),
    ('THETA', 'THETA'),
    ('XLM', 'XLM'),
    ('VET', 'VET'),
    ('FIL', 'FIL'),
    ('TRX', 'TRX'),
    ('AAVE', 'AAVE'),
    ('XMR', 'XMR'),
    ('EOS', 'EOS'),
    ('CAKE', 'CAKE'),
    ('MKR', 'MKR'),
    ('ALGO', 'ALGO'),
    ('ATOM', 'ATOM'),
    ('FTT', 'FTT'),
    ('NEO', 'NEO'),
    ('IOTA', 'IOTA'),
    ('XTZ', 'XTZ'),
    ('UNI', 'UNI'),
    ('AVAX', 'AVAX'),
    ('KSM', 'KSM'),
    ('WAVES', 'WAVES'),
    ('EGLD', 'EGLD'),
    ('HBAR', 'HBAR'),
    ('CHZ', 'CHZ'),
    ('ZEC', 'ZEC'),
    ('DASH', 'DASH'),
    ('YFI', 'YFI'),
    ('SNX', 'SNX'),
    ('SUSHI', 'SUSHI'),
    ('ENJ', 'ENJ'),
    ('NEAR', 'NEAR'),
    ('ZIL', 'ZIL'),
]

#
# THIRD_CHOISE_ETH = [
#     ('ETH', 'ETH'),
# ]